{
    "atomType": "Molecule",
    "name": "Involute Gear",
    "x": 0,
    "y": 0,
    "uniqueID": 623227,
    "ioValues": [
        {
            "name": "Number Of Teeth",
            "ioValue": 10
        },
        {
            "name": "Circular Pitch",
            "ioValue": 10
        }
    ],
    "topLevel": true,
    "allAtoms": [
        {
            "atomType": "Input",
            "name": "Number Of Teeth",
            "x": 0.013333333333333334,
            "y": 0.42528735632183906,
            "uniqueID": 413161,
            "ioValues": []
        },
        {
            "atomType": "Code",
            "name": "Code",
            "x": 0.415311004784689,
            "y": 0.38697318007662834,
            "uniqueID": 644051,
            "ioValues": [],
            "code": "//Ported from https://risacher.org/OpenJsCad/gearsdemo.html\n\n\nfunction main(numTeeth, circularPitch, pressureAngle, clearance, thickness){\n  return involuteGear(10,5,20,0,5)\n}\n\nreturn main(numTeeth, circularPitch, pressureAngle, clearance, thickness)\n\nfunction involuteGear(numTeeth, circularPitch, pressureAngle, clearance, thickness){\n    \n  // default values:\n  if(arguments.length < 3) pressureAngle = 20;\n  if(arguments.length < 4) clearance = 0;\n  if(arguments.length < 4) thickness = 1;\n  \n  var addendum = circularPitch / Math.PI;\n  var dedendum = addendum + clearance;\n  \n  // radiuses of the 4 circles:\n  var pitchRadius = numTeeth * circularPitch / (2 * Math.PI);\n  var baseRadius = pitchRadius * Math.cos(Math.PI * pressureAngle / 180);\n  var outerRadius = pitchRadius + addendum;\n  var rootRadius = pitchRadius - dedendum; \n\n  var maxtanlength = Math.sqrt(outerRadius*outerRadius - baseRadius*baseRadius);\n  var maxangle = maxtanlength / baseRadius;\n\n  var tl_at_pitchcircle = Math.sqrt(pitchRadius*pitchRadius - baseRadius*baseRadius);\n  var angle_at_pitchcircle = tl_at_pitchcircle / baseRadius;\n  var diffangle = angle_at_pitchcircle - Math.atan(angle_at_pitchcircle);\n  var angularToothWidthAtBase = Math.PI / numTeeth + 2*diffangle;\n  \n  // build a single 2d tooth in the 'points' array:\n  var resolution = 5;\n  var points = [vec2.create(0,0)];\n  for(var i = 0; i <= resolution; i++)\n  {\n    // first side of the tooth:\n    var angle = maxangle * i / resolution;\n    var tanlength = angle * baseRadius;\n    var radvector = vec2.fromAngleRadians(angle);\n    var tanvector = vec2.scale(-1,vec2.normal(radvector));\n    \n    var p = vec2.add(vec2.scale(baseRadius, radvector), vec2.scale(tanlength,tanvector));\n    \n    points[i+1] = p;\n    \n    // opposite side of the tooth:\n    radvector = vec2.fromAngleRadians(angularToothWidthAtBase - angle);    \n    tanvector = vec2.normal(radvector);\n    \n    p = vec2.add(vec2.scale(baseRadius, radvector), vec2.scale(tanlength, tanvector));\n    points[2 * resolution + 2 - i] = p;\n  }\n  \n  // create the polygon and extrude into 3D:\n    \n    var tooth3d = extrudeLinear({height: thickness}, geom2.fromPoints(points))\n    \n     var allteeth = []\n     for(var i = 0; i < numTeeth; i++){\n        console.log(i)\n        var angle = Math.PI*(i*360/numTeeth)/180;\n        var rotatedtooth = rotate([0,0,angle],tooth3d);\n        console.log(\"here\")\n        allteeth.push(rotatedtooth);\n     }\n     \n     allteeth = union(allteeth)\n     \n       // build the root circle:  \n     points = [];\n     var toothAngle = 2 * Math.PI / numTeeth;\n     var toothCenterAngle = 0.5 * angularToothWidthAtBase; \n     for(var i = 0; i < numTeeth; i++){\n        var angle = toothCenterAngle + i * toothAngle;\n        var p = vec2.scale(rootRadius, vec2.fromAngleRadians(angle));\n        points.push(p);\n     }\n\n     // create the polygon and extrude into 3D:\n     var rootcircle = extrudeLinear({height: thickness}, geom2.fromPoints(points))\n    \n    return union(rootcircle, allteeth)\n}"
        },
        {
            "atomType": "Input",
            "name": "Circular Pitch",
            "x": 0.013333333333333334,
            "y": 0.6590038314176245,
            "uniqueID": 853939,
            "ioValues": []
        },
        {
            "atomType": "Output",
            "name": "Output",
            "x": 0.9853587115666179,
            "y": 0.5,
            "ioValues": []
        }
    ],
    "allConnectors": [
        {
            "ap1Name": "geometry",
            "ap2Name": "number or geometry",
            "ap2Primary": false,
            "ap1ID": 644051
        }
    ],
    "fileTypeVersion": 1,
    "filetypeVersion": 1,
    "circleSegmentSize": 2
}